export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const LOGOUT = 'LOGOUT';

export const FETCH_NEWS_START = 'FETCH_NEWS_START';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAIL = 'FETCH_NEWS_FAIL';

export const ADD_NEWS_START = 'ADD_NEWS_START';
export const ADD_NEWS_SUCCESS = 'ADD_NEWS_SUCCESS';
export const ADD_NEWS_FAIL = 'ADD_NEWS_FAIL';

export const UPDATE_NEWS_START = 'UPDATE_NEWS_START';
export const UPDATE_NEWS_SUCCESS = 'UPDATE_NEWS_SUCCESS';
export const UPDATE_NEWS_FAIL = 'UPDATE_NEWS_FAIL';
export const CLEAR_UPDATE = 'CLEAR_UPDATE';

export const DELETE_NEWS_START = 'DELETE_NEWS_START';
export const DELETE_NEWS_SUCCESS = 'DELETE_NEWS_SUCCESS';
export const DELETE_NEWS_FAIL = 'DELETE_NEWS_FAIL';

export const FETCH_AVAILABILITY_START = 'FETCH_AVAILABILITY_START';
export const FETCH_AVAILABILITY_SUCCESS = 'FETCH_AVAILABILITY_SUCCESS';
export const FETCH_AVAILABILITY_FAIL = 'FETCH_AVAILABILITY_FAIL';

export const INITIATE_BOOKING_START = 'INITIATE_BOOKING_START';
export const INITIATE_BOOKING_SUCCESS = 'INITIATE_BOOKING_SUCCESS';
export const INITIATE_BOOKING_FAIL = 'INITIATE_BOOKING_FAIL';

export const INITIATE_PAYMENT_START = 'INITIATE_PAYMENT_START';
export const INITIATE_PAYMENT_SUCCESS = 'INITIATE_PAYMENT_SUCCESS';
export const INITIATE_PAYMENT_FAIL = 'INITIATE_PAYMENT_FAIL';

export const RESET_BOOKING = 'RESET_BOOKING';

export const FINALISE_BOOKING_START = 'FINALISE_BOOKING_START';
export const FINALISE_BOOKING_SUCCESS = 'FINALISE_BOOKING_SUCCESS';
export const FINALISE_BOOKING_FAIL = 'FINALISE_BOOKING_FAIL';

export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_START = 'ADD_COMMENT_START';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';

export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_START = 'DELETE_COMMENT_START';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

export const RESET_COMMENT = 'RESET_COMMENT';

export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const VERIFY_EMAIL = 'VERIFY_EMAIL';
export const VERIFY_FAIL = 'VERIFY_FAIL';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_START = 'VERIFY_START';

export const CLEAR_NEWS_ERROR = 'CLEAR_NEWS_ERROR';

export const BOOKING_SEARCH_START = 'BOOKING_SEARCH_START';
export const BOOKING_SEARCH_FAIL = 'BOOKING_SEARCH_FAIL';
export const BOOKING_SEARCH_SUCCESS = 'BOOKING_SEARCH_SUCCESS';

export const DELETE_SEARCH_START = 'DELETE_SEARCH_START';
export const DELETE_SEARCH_SUCCESS = 'DELETE_SEARCH_SUCCESS';
export const DELETE_SEARCH_FAIL = 'DELETE_SEARCH_FAIL';

export const EDIT_SEARCH_START = 'EDIT_SEARCH_START';
export const EDIT_SEARCH_SUCCESS = 'EDIT_SEARCH_SUCCESS';
export const EDIT_SEARCH_FAIL = 'EDIT_SEARCH_FAIL';

export const CLEAR_QUERY_STATUS = 'CLEAR_QUERY_STATUS';
